import React from "react";
import styled from "styled-components";

type Props = {
  style?: React.CSSProperties;
  className?: string;
};

const SvgLogo = styled.svg`
  fill: white;
`;

export function Logo({ style, className }: Props) {
  return (
    <SvgLogo
      version="1.1"
      viewBox="0 0 330 140"
      preserveAspectRatio="xMidYMid meet"
      aria-labelledby="title"
      role="img"
      data-reactid=".0.0.0"
      style={style}
      className={className}
    >
      <title data-reactid=".0.0.0.0">Video Tagger Rx</title>
      <g
        data-character="v"
        transform="translate(0, 0)"
        data-reactid=".0.0.0.1:0"
      >
        <rect
          x="0"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:0.0"
        ></rect>
        <rect
          x="40"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:0.1"
        ></rect>
        <rect
          x="0"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:0.2"
        ></rect>
        <rect
          x="40"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:0.3"
        ></rect>
        <rect
          x="10"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:0.4"
        ></rect>
        <rect
          x="30"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:0.5"
        ></rect>
        <rect
          x="10"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:0.6"
        ></rect>
        <rect
          x="30"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:0.7"
        ></rect>
        <rect
          x="20"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:0.8"
        ></rect>
      </g>
      <g
        data-character="i"
        transform="translate(60, 0)"
        data-reactid=".0.0.0.1:1"
      >
        <rect
          x="0"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:1.0"
        ></rect>
        <rect
          x="0"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:1.1"
        ></rect>
        <rect
          x="0"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:1.2"
        ></rect>
        <rect
          x="0"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:1.3"
        ></rect>
        <rect
          x="0"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:1.4"
        ></rect>
      </g>
      <g
        data-character="d"
        transform="translate(80, 0)"
        data-reactid=".0.0.0.1:2"
      >
        <rect
          x="0"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.0"
        ></rect>
        <rect
          x="10"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.1"
        ></rect>
        <rect
          x="20"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.2"
        ></rect>
        <rect
          x="0"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.3"
        ></rect>
        <rect
          x="30"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.4"
        ></rect>
        <rect
          x="0"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.5"
        ></rect>
        <rect
          x="30"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.6"
        ></rect>
        <rect
          x="0"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.7"
        ></rect>
        <rect
          x="30"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.8"
        ></rect>
        <rect
          x="0"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.9"
        ></rect>
        <rect
          x="10"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.a"
        ></rect>
        <rect
          x="20"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:2.b"
        ></rect>
      </g>
      <g
        className="character"
        data-character="e"
        transform="translate(130, 0)"
        data-reactid=".0.0.0.1:3"
      >
        <rect
          x="0"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:3.0"
        ></rect>
        <rect
          x="10"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:3.1"
        ></rect>
        <rect
          x="20"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:3.2"
        ></rect>
        <rect
          x="0"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:3.3"
        ></rect>
        <rect
          x="0"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:3.4"
        ></rect>
        <rect
          x="10"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:3.5"
        ></rect>
        <rect
          x="20"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:3.6"
        ></rect>
        <rect
          x="0"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:3.7"
        ></rect>
        <rect
          x="0"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:3.8"
        ></rect>
        <rect
          x="10"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:3.9"
        ></rect>
        <rect
          x="20"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:3.a"
        ></rect>
      </g>
      <g
        className="character"
        data-character="o"
        transform="translate(170, 0)"
        data-reactid=".0.0.0.1:4"
      >
        <rect
          x="10"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:4.0"
        ></rect>
        <rect
          x="20"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:4.1"
        ></rect>
        <rect
          x="0"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:4.2"
        ></rect>
        <rect
          x="30"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:4.3"
        ></rect>
        <rect
          x="0"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:4.4"
        ></rect>
        <rect
          x="30"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:4.5"
        ></rect>
        <rect
          x="0"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:4.6"
        ></rect>
        <rect
          x="30"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:4.7"
        ></rect>
        <rect
          x="10"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:4.8"
        ></rect>
        <rect
          x="20"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:4.9"
        ></rect>
      </g>
      <g
        className="character"
        data-character=" "
        transform="translate(220, 0)"
        data-reactid=".0.0.0.1:5"
      >
        <rect
          x="10"
          y="0"
          width="10"
          height="10"
          fill="rgba(0, 0, 0, 0)"
          data-reactid=".0.0.0.1:5.0"
        ></rect>
      </g>
      <g
        className="character"
        data-character="t"
        transform="translate(0, 70)"
        data-reactid=".0.0.0.1:7"
      >
        <rect
          x="0"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:7.0"
        ></rect>
        <rect
          x="10"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:7.1"
        ></rect>
        <rect
          x="20"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:7.2"
        ></rect>
        <rect
          x="10"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:7.3"
        ></rect>
        <rect
          x="10"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:7.4"
        ></rect>
        <rect
          x="10"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:7.5"
        ></rect>
        <rect
          x="10"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:7.6"
        ></rect>
      </g>
      <g
        className="character"
        data-character="a"
        transform="translate(40, 70)"
        data-reactid=".0.0.0.1:8"
      >
        <rect
          x="10"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.0"
        ></rect>
        <rect
          x="20"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.1"
        ></rect>
        <rect
          x="0"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.2"
        ></rect>
        <rect
          x="30"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.3"
        ></rect>
        <rect
          x="0"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.4"
        ></rect>
        <rect
          x="10"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.5"
        ></rect>
        <rect
          x="20"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.6"
        ></rect>
        <rect
          x="30"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.7"
        ></rect>
        <rect
          x="0"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.8"
        ></rect>
        <rect
          x="30"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.9"
        ></rect>
        <rect
          x="0"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.a"
        ></rect>
        <rect
          x="30"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:8.b"
        ></rect>
      </g>
      <g
        className="character"
        data-character="g"
        transform="translate(90, 70)"
        data-reactid=".0.0.0.1:9"
      >
        <rect
          x="10"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:9.0"
        ></rect>
        <rect
          x="20"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:9.1"
        ></rect>
        <rect
          x="30"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:9.2"
        ></rect>
        <rect
          x="0"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:9.3"
        ></rect>
        <rect
          x="0"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:9.4"
        ></rect>
        <rect
          x="20"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:9.5"
        ></rect>
        <rect
          x="30"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:9.6"
        ></rect>
        <rect
          x="0"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:9.7"
        ></rect>
        <rect
          x="30"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:9.8"
        ></rect>
        <rect
          x="10"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:9.9"
        ></rect>
        <rect
          x="20"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:9.a"
        ></rect>
      </g>
      <g
        className="character"
        data-character="g"
        transform="translate(140, 70)"
        data-reactid=".0.0.0.1:a"
      >
        <rect
          x="10"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:a.0"
        ></rect>
        <rect
          x="20"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:a.1"
        ></rect>
        <rect
          x="30"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:a.2"
        ></rect>
        <rect
          x="0"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:a.3"
        ></rect>
        <rect
          x="0"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:a.4"
        ></rect>
        <rect
          x="20"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:a.5"
        ></rect>
        <rect
          x="30"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:a.6"
        ></rect>
        <rect
          x="0"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:a.7"
        ></rect>
        <rect
          x="30"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:a.8"
        ></rect>
        <rect
          x="10"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:a.9"
        ></rect>
        <rect
          x="20"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:a.a"
        ></rect>
      </g>
      <g
        className="character"
        data-character="e"
        transform="translate(190, 70)"
        data-reactid=".0.0.0.1:b"
      >
        <rect
          x="0"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:b.0"
        ></rect>
        <rect
          x="10"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:b.1"
        ></rect>
        <rect
          x="20"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:b.2"
        ></rect>
        <rect
          x="0"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:b.3"
        ></rect>
        <rect
          x="0"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:b.4"
        ></rect>
        <rect
          x="10"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:b.5"
        ></rect>
        <rect
          x="20"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:b.6"
        ></rect>
        <rect
          x="0"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:b.7"
        ></rect>
        <rect
          x="0"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:b.8"
        ></rect>
        <rect
          x="10"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:b.9"
        ></rect>
        <rect
          x="20"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:b.a"
        ></rect>
      </g>
      <g
        className="character"
        data-character="r"
        transform="translate(230, 70)"
        data-reactid=".0.0.0.1:c"
      >
        <rect
          x="0"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.0"
        ></rect>
        <rect
          x="10"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.1"
        ></rect>
        <rect
          x="20"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.2"
        ></rect>
        <rect
          x="0"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.3"
        ></rect>
        <rect
          x="30"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.4"
        ></rect>
        <rect
          x="0"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.5"
        ></rect>
        <rect
          x="10"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.6"
        ></rect>
        <rect
          x="20"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.7"
        ></rect>
        <rect
          x="0"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.8"
        ></rect>
        <rect
          x="20"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.9"
        ></rect>
        <rect
          x="0"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.a"
        ></rect>
        <rect
          x="30"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:c.b"
        ></rect>
      </g>
      <g
        className="character"
        data-character=" "
        transform="translate(280, 70)"
        data-reactid=".0.0.0.1:d"
      >
        <rect
          x="10"
          y="0"
          width="10"
          height="10"
          fill="rgba(0, 0, 0, 0)"
          data-reactid=".0.0.0.1:d.0"
        ></rect>
      </g>
      <g
        className="character"
        data-character="r"
        transform="translate(0, 140)"
        data-reactid=".0.0.0.1:f"
        style={{ transform: "translate(234px, 0px) scale(1.2)" }}
      >
        <rect
          x="0"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.0"
        ></rect>
        <rect
          x="10"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.1"
        ></rect>
        <rect
          x="20"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.2"
        ></rect>
        <rect
          x="0"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.3"
        ></rect>
        <rect
          x="30"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.4"
        ></rect>
        <rect
          x="0"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.5"
        ></rect>
        <rect
          x="10"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.6"
        ></rect>
        <rect
          x="20"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.7"
        ></rect>
        <rect
          x="0"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.8"
        ></rect>
        <rect
          x="20"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.9"
        ></rect>
        <rect
          x="0"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.a"
        ></rect>
        <rect
          x="30"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:f.b"
        ></rect>
      </g>
      <g
        className="character"
        data-character="x"
        transform="translate(50, 140)"
        data-reactid=".0.0.0.1:g"
        style={{ transform: "translate(284px, 37px) scale(0.8)" }}
      >
        <rect
          x="0"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:g.0"
        ></rect>
        <rect
          x="40"
          y="10"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:g.1"
        ></rect>
        <rect
          x="10"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:g.2"
        ></rect>
        <rect
          x="30"
          y="20"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:g.3"
        ></rect>
        <rect
          x="20"
          y="30"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:g.4"
        ></rect>
        <rect
          x="10"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:g.5"
        ></rect>
        <rect
          x="30"
          y="40"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:g.6"
        ></rect>
        <rect
          x="0"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:g.7"
        ></rect>
        <rect
          x="40"
          y="50"
          width="10"
          height="10"
          data-reactid=".0.0.0.1:g.8"
        ></rect>
      </g>
    </SvgLogo>
  );
}
